apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: quay.io/argoproj/argocd
    newTag: v2.10.1

resources:
# argocd namespace
- argocd-ns.yaml
# argocd core installation manifests
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.1/manifests/install.yaml
# application set that automates applications management 
- applicationset.yaml
# cluster metadata
- in-cluster.yaml
# argocd project for system applications
- system-project.yaml
# https://github.com/argoproj-labs/argocd-vault-plugin/tree/main/manifests/cmp-sidecar
- vault-plugin/cmp-plugin.yaml

patches:
- path: argocd-cm.yaml

patchesStrategicMerge:
- vault-plugin/argocd-repo-server.yaml

namespace: argocd