apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.9.13
    createNamespace: true
    valuesFile: values.yaml
